stages:
  - build
  - test
  - deploy

Docker E2E:
  stage: build
  image: docker:stable@sha256:aaead6545f3f63850ba8cbd1cf9cbe85e0cc9a512ec4d23060b0b69c5d72680e

  services:
    - docker:dind@sha256:ad5b5195369a35265a33701ebea33065fa4c444de99bddece07637cff061afd7

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    changes:
      - Dockerfile


.base:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

  before_script:
    - sudo chown -R user:user /builds/gitlab
    - npm install --no-audit --prefer-offline --progress=false


test:
  extends: .base
  script:
    - npm test

build:
  extends: .base
  script:
    - npm run build
  artifacts:
    paths: [www]
    expire_in: 1 month

pages:
  extends: .base
  stage: deploy
  script:
    - mv www public
  artifacts:
    paths: [public]
  only:
    - master


