stages:
  - build
  - test
  - deploy

Docker E2E:
  stage: build
  image: docker:stable@sha256:bc7f740e2c0a8a9ec43b009b7cd35aafb10e69488a017110ad723003fbd3a7ae

  services:
    - docker:dind@sha256:c260a7abfc7f5f8c20eb3918d5fce58c17018d6d9490ce1b3a950d9aa9e404ae

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    changes:
      - Dockerfile


.base:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

  before_script:
    - sudo chown -R user:user /builds/gitlab
    - npm install --no-audit --prefer-offline --progress=false


test:
  extends: .base
  script:
    - npm test

build:
  extends: .base
  script:
    - npm run build
  artifacts:
    paths: [www]
    expire_in: 1 month

pages:
  extends: .base
  stage: deploy
  script:
    - mv www public
  artifacts:
    paths: [public]
  only:
    - master


