image: node:11

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install


test:
  before_script:
    - npm install
    - apt-get update --quiet
    - apt-get install --yes --quiet chromium
  script:
    - npm run test


pages:
  script:
    - npm run build
    - mv www public
  artifacts:
    paths:
      - public
