stages:
  - build
  - test
  - deploy

Docker E2E:
  stage: build
  image: docker:stable@sha256:fd4d028713fd05a1fb896412805daed82c4a0cc84331d8dad00cb596d7ce3e3a

  services:
    - docker:dind@sha256:a8e3e616dc41cda6fb53cd54b8a5fc8ee9b5f026a8d178782be547ba2ef47618

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    changes:
      - Dockerfile

.base:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

  before_script:
    - sudo chown -R user:user /builds/gitlab
    - npm install --no-audit --prefer-offline --progress=false

test:
  extends: .base
  script:
    - npm test

build:
  extends: .base
  script:
    - npm run build
  artifacts:
    paths: [www]
    expire_in: 1 month

pages:
  extends: .base
  stage: deploy
  script:
    - mv www public
  artifacts:
    paths: [public]
  only:
    - master
