stages:
  - build
  - test
  - deploy

Docker E2E:
  stage: build
  image: docker:stable@sha256:fd4d028713fd05a1fb896412805daed82c4a0cc84331d8dad00cb596d7ce3e3a

  services:
    - docker:dind@sha256:ca2744235df40f184843b2cb9f0245a6b64ae65065aad30285e80d5a266fe0c2

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    changes:
      - Dockerfile

.base:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

  before_script:
    - sudo chown -R user:user /builds/gitlab
    - npm install --no-audit --prefer-offline --progress=false

test:
  extends: .base
  script:
    - npm test

build:
  extends: .base
  script:
    - npm run build
  artifacts:
    paths: [dist, loader, www]
    expire_in: 1 month

lint:
  extends: .base
  script:
    - npm run lint
  allow_failure: true

prettier:
  extends: .base
  script:
    - npx prettier --check .

pages:
  extends: .base
  stage: deploy
  script:
    - mv www public
  artifacts:
    paths: [public]
  only:
    - master

push:
  stage: deploy
  image: ubuntu:20.04@sha256:8ae9bafbb64f63a50caab98fd3a5e37b3eb837a3e0780b78e5218e63193961f9
  only:
    - master
  dependencies:
    - build

  before_script:
    - apt update
    - apt install -y git rsync
    - git config --global user.email 'gitlab@xikolo.de'
    - git config --global user.name 'GitLab CI'

  script:
    - git clone -b build https://gitlab-ci:$GITLAB_CI_TOKEN@dev.xikolo.de/gitlab/$CI_PROJECT_PATH.git build
    - rsync --recursive --links --delete --verbose dist/ build/dist/
    - rsync --recursive --links --delete --verbose loader/ build/loader/
    - cd build/
    - git add .
    - git commit -m"Auto-build for $CI_COMMIT_SHA" && git push; true
