/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XmControls {}
  interface XmMedia {}
  interface XmPlayer {}
  interface XmScreen {
    'pip': boolean;
  }
  interface XmVideo {
    'currentTime': () => Promise<number>;
    'getAspectRatio': () => Promise<number>;
    'getDimensions': () => Promise<{ width: number; height: number; }>;
    'getDuration': () => Promise<number>;
    'pause': () => Promise<void>;
    'play': () => Promise<void>;
    'seek': (seconds: number) => Promise<number>;
    /**
    * Vimeo Video ID
    */
    'src': number;
  }
}

declare global {


  interface HTMLXmControlsElement extends Components.XmControls, HTMLStencilElement {}
  var HTMLXmControlsElement: {
    prototype: HTMLXmControlsElement;
    new (): HTMLXmControlsElement;
  };

  interface HTMLXmMediaElement extends Components.XmMedia, HTMLStencilElement {}
  var HTMLXmMediaElement: {
    prototype: HTMLXmMediaElement;
    new (): HTMLXmMediaElement;
  };

  interface HTMLXmPlayerElement extends Components.XmPlayer, HTMLStencilElement {}
  var HTMLXmPlayerElement: {
    prototype: HTMLXmPlayerElement;
    new (): HTMLXmPlayerElement;
  };

  interface HTMLXmScreenElement extends Components.XmScreen, HTMLStencilElement {}
  var HTMLXmScreenElement: {
    prototype: HTMLXmScreenElement;
    new (): HTMLXmScreenElement;
  };

  interface HTMLXmVideoElement extends Components.XmVideo, HTMLStencilElement {}
  var HTMLXmVideoElement: {
    prototype: HTMLXmVideoElement;
    new (): HTMLXmVideoElement;
  };
  interface HTMLElementTagNameMap {
    'xm-controls': HTMLXmControlsElement;
    'xm-media': HTMLXmMediaElement;
    'xm-player': HTMLXmPlayerElement;
    'xm-screen': HTMLXmScreenElement;
    'xm-video': HTMLXmVideoElement;
  }
}

declare namespace LocalJSX {
  interface XmControls extends JSXBase.HTMLAttributes<HTMLXmControlsElement> {
    'onPause'?: (event: CustomEvent<any>) => void;
    'onPlay'?: (event: CustomEvent<any>) => void;
  }
  interface XmMedia extends JSXBase.HTMLAttributes<HTMLXmMediaElement> {}
  interface XmPlayer extends JSXBase.HTMLAttributes<HTMLXmPlayerElement> {}
  interface XmScreen extends JSXBase.HTMLAttributes<HTMLXmScreenElement> {
    'pip'?: boolean;
  }
  interface XmVideo extends JSXBase.HTMLAttributes<HTMLXmVideoElement> {
    /**
    * Vimeo Video ID
    */
    'src'?: number;
  }

  interface IntrinsicElements {
    'xm-controls': XmControls;
    'xm-media': XmMedia;
    'xm-player': XmPlayer;
    'xm-screen': XmScreen;
    'xm-video': XmVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


