/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Status,
} from './utils/status';

export namespace Components {
  interface XmAspectRatioBox {
    'ratio': number;
  }
  interface XmControls {
    'status': Status;
  }
  interface XmPlayer {
    'pause': () => Promise<void>;
    'play': () => Promise<void>;
    'seek': (seconds: number) => Promise<void>;
  }
  interface XmScreen {
    'pip': boolean;
  }
  interface XmVideo {
    'currentTime': () => Promise<number>;
    'getAspectRatio': () => Promise<number>;
    'getDimensions': () => Promise<{ width: number; height: number; }>;
    'getDuration': () => Promise<number>;
    'pause': () => Promise<void>;
    'play': () => Promise<void>;
    'seek': (seconds: number) => Promise<number>;
    /**
    * Vimeo Video ID
    */
    'src': number;
  }
}

declare global {


  interface HTMLXmAspectRatioBoxElement extends Components.XmAspectRatioBox, HTMLStencilElement {}
  var HTMLXmAspectRatioBoxElement: {
    prototype: HTMLXmAspectRatioBoxElement;
    new (): HTMLXmAspectRatioBoxElement;
  };

  interface HTMLXmControlsElement extends Components.XmControls, HTMLStencilElement {}
  var HTMLXmControlsElement: {
    prototype: HTMLXmControlsElement;
    new (): HTMLXmControlsElement;
  };

  interface HTMLXmPlayerElement extends Components.XmPlayer, HTMLStencilElement {}
  var HTMLXmPlayerElement: {
    prototype: HTMLXmPlayerElement;
    new (): HTMLXmPlayerElement;
  };

  interface HTMLXmScreenElement extends Components.XmScreen, HTMLStencilElement {}
  var HTMLXmScreenElement: {
    prototype: HTMLXmScreenElement;
    new (): HTMLXmScreenElement;
  };

  interface HTMLXmVideoElement extends Components.XmVideo, HTMLStencilElement {}
  var HTMLXmVideoElement: {
    prototype: HTMLXmVideoElement;
    new (): HTMLXmVideoElement;
  };
  interface HTMLElementTagNameMap {
    'xm-aspect-ratio-box': HTMLXmAspectRatioBoxElement;
    'xm-controls': HTMLXmControlsElement;
    'xm-player': HTMLXmPlayerElement;
    'xm-screen': HTMLXmScreenElement;
    'xm-video': HTMLXmVideoElement;
  }
}

declare namespace LocalJSX {
  interface XmAspectRatioBox extends JSXBase.HTMLAttributes<HTMLXmAspectRatioBoxElement> {
    'ratio'?: number;
  }
  interface XmControls extends JSXBase.HTMLAttributes<HTMLXmControlsElement> {
    'onControl:pause'?: (event: CustomEvent<any>) => void;
    'onControl:play'?: (event: CustomEvent<any>) => void;
    'onControl:seek'?: (event: CustomEvent<any>) => void;
    'status'?: Status;
  }
  interface XmPlayer extends JSXBase.HTMLAttributes<HTMLXmPlayerElement> {}
  interface XmScreen extends JSXBase.HTMLAttributes<HTMLXmScreenElement> {
    'pip'?: boolean;
  }
  interface XmVideo extends JSXBase.HTMLAttributes<HTMLXmVideoElement> {
    /**
    * Vimeo Video ID
    */
    'src'?: number;
  }

  interface IntrinsicElements {
    'xm-aspect-ratio-box': XmAspectRatioBox;
    'xm-controls': XmControls;
    'xm-player': XmPlayer;
    'xm-screen': XmScreen;
    'xm-video': XmVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


