name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.lock') }}
          restore-keys: ${{ runner.os }}-node-
      # - run: sudo chown -R user:user $(pwd)
      - run: npm install --no-audit --prefer-offline --progress=false
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build job"

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint job"

  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: echo "prettier job"
